modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="lostdepths"
version="1.18.0"
displayName="LostDepths"
displayURL="https://blackdragoncz.cz/"
logoFile="logo.png"
credits="Structures: SniperMan_CZ | Models: AsLan, Polygony, MikMikTG, Muurr | Textures: ConfusionFloof, MikMikTG , Muurr"
authors="BlackDragonCZ, SamCZEK"
description="Add ancient mystery of underground and past."

[[dependencies.lostdepths]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"



[[dependencies.lostdepths]]
    modId="patchouli"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lostdepths]]
    modId="geckolib"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.lostdepths]]
    modId="jei"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

